<?php

namespace App\Modules\Admin\Services;

use App\Models\System\Version;

class VersionService extends BaseService
{
    public function __construct(Version $version)
    {
        $this->model = $version;
    }

    public function lists(array $params): array
    {
        $params['where_callback'] = function($query) use ($params){
            $request = request();
            // 按照名称进行搜索
            if (!empty($search = $request->input('search', ''))){
                $query->where(function($query)use ($search){
                    $query->where('version_name', 'LIKE', '%' . trim($search) . '%')
                          ->orWhere('version_number', 'LIKE', '%' . trim($search) . '%');
                });
            }
        };
        $params['order'] = 'version_sort';
        $params['order_sort'] = 'ASC';
        return parent::lists($params); // TODO: Change the autogenerated stub
    }
}
