<?php

namespace App\Modules\Admin\Services;

use App\Models\System\Banner;

class BannerService extends BaseService
{
    public function __construct(Banner $banner)
    {
        $this->model = $banner;
    }

    public function lists(array $params): array
    {
        $params['where_callback'] = function($query) use ($params){
            $request = request();
            // 按照名称进行搜索
            if (!empty($search = $request->input('search', ''))){
                $query->where('banner_title', 'LIKE', '%' . trim($search) . '%');
            }
            // 状态
            $is_check = $request->input('is_check', -1);
            if ($is_check > -1){
                $query->where('is_check', '=', $is_check);
            }
        };
        $params['order'] = 'banner_sort';
        $params['order_sort'] = 'ASC';
        return parent::lists($params); // TODO: Change the autogenerated stub
    }
}
